on:
  push:
    branches:
      - main
jobs:
  backend:
    name: Deploy Backend to Railway
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"
          cache: maven

      - name: Build Spring Boot
        # ⬇️ change if your backend lives elsewhere
        working-directory: ./lyrics-api-springboot
        run: mvn -B clean package -DskipTests

      - name: Set up Node.js (for Railway CLI)
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Authenticate Railway CLI
        run: railway login --ci $RAILWAY_TOKEN
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway
        working-directory: ./lyrics-api-springboot
        run: railway up --detached --project ${{ secrets.RAILWAY_PROJECT_ID }}
